#!/bin/bash

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database $DB_NAME does not exist, skipping $0"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    echo "Database $DB_NAME not initialized, skipping $0"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    echo "Database $DB_NAME not initialized, skipping $0"
    exit 0
fi

click-odoo-update --if-exists -d "$DB_NAME" --i18n-overwrite
